import { MathJax, MathJaxContext } from 'better-react-mathjax'


# try...catch


The `try...catch` statement is powerful and useful. Reason being, it makes code robust, safe and error-proof.

:::info

Throwing `exceptions` isn't always the best error-handling method. 

A `try...catch` lets you execute things with access to the error, thereby resolving it.
:::

- Structurally, a `try...catch` statement has a `try` block, then a `catch` block, `finally` block, or both. 

- The code in the `try` block is executed first. If the `try` throws an exception or error: 

    - Then the code in the `catch/finally` block is executed. 

- Note that when there is a `finally` block, it will always be executed before control flow exits the `try...catch` construct. 

Overall this statement **tries** to perform an action, and if trying **fails**, you can **catch** the resulting errors and hopefully resolve them.


The basic syntax is the following:

```js
try {
    tryStatements
} catch (exceptionVar) {
    catchStatements
} finally {
    finallyStatements
}
```

- The `exceptionVar` is an optional identifier to hold the caught exception. 

    - If you don't need this, ignore it - write `catch { catchStatements }`.

- An exception being thrown in the `try` block immediately leads the control flow to `catch`. 

- If `finally` is part of the statement, it will always be exected before control flow leaves the whole `try...catch` block.

Let's see an example:

<iframe
    src="https://hlab.app/s/docs/trycatch2_hbook"
    width="100%"
    height="800px"
/>

:::tip
A great use case of `try...catch` is to only catch (and silence) a small subset of expected errors, say RangeErrors.

As for other errors, just re-throw them if they're not relevant in your scenario. 

For example: `if (e instanceof RangeError) { //handle range error} else { throw e; }`
:::

The optional exception identifier can provide detailed info regarding the thrown Error/Exception.

Here's an example where the exception identifier isn't needed at all:

<iframe
    src="https://hlab.app/s/docs/trycatch_hbook"
    width="100%"
    height="500px"/>


One example of using a `finally` block is: During a file opening you `try` to write data. 

Whether or not an exception occurs and is handled via `catch`... `finally` will run. A good thing to add in `finally` is closing a file.

Lastly, let's give an example combining mentioned things:

<iframe
    src="https://hlab.app/s/docs/trycatch3_hbook"
    width="100%"
    height="650px"/>

- Overall, one should get familiar with `try...catch...finally` statements and use them often. 

- It's a great way of handling exceptions and errors, and you can even do nothing in the catch block but just throw the exception!

    - which is virtually identical to `if() { throw new Exception() }`! 


